Finish mobile version
Kaghenimbale/my-portfolio pull request #2
Opened 2023-01-12 15:49 UTC by Kaghenimbale

## For this Personal Portfolio project, I have done the following steps:
* [ ]  I add the works section
* [ ]  Modify the about me section
* [ ]   Add the ul li list item in the about me
* [ ]  Use CSS grid and flexbox

2023-01-12 16:44 UTC, christianbiring1 requested changes
Hi @Kaghenimbale , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/212127805-1a450359-c2c7-4d16-bd8e-9612f6742264.gif)


## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR`title` and `summary`
- [ ] The flexbox is used correctly to place the items on the page :art: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 16:44 UTC, christianbiring1 commented on README.md
> +
- [ ] Kindly make sure you have provided the command to clone the repos, and navigate through it ...

2023-01-12 16:44 UTC, christianbiring1 commented on README.md
> +<!--
- [ ] Kindly make sure you provide the commands.
`Hint: YOu may say`
```sh
cd <directory_name>
Open the index.html in the browser
...
```

2023-01-12 16:44 UTC, christianbiring1 commented on README.md
> +
- [ ]   YOu may consider providing the command to checks the linters errors.

2023-01-12 16:44 UTC, christianbiring1 commented on style.css
> +  font-family: Verdana, Geneva, Tahoma, sans-serif;
- [ ] Kindly make sure you stick to the design as much as you can. the typo and the spacing are supposed to match the Figma design. make sure you fix that.
Hint: In Figma they use `Roboto` you will need to use the `google fonts service`
You may check [here](https://www.youtube.com/watch?v=qgmLDPLApBY) how to do so

2023-01-12 16:44 UTC, christianbiring1 commented on style.css
> +  line-height: 1.5;
- [ ] Kindly make sure you do not have any kind of scroll in any of the sections on your page as you may notice how all of them are. `The introduction part, the let's connect text.` 
`Hint: You may consider removing the height:80vh applied on this section and the different line-height.`
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/212122644-419707a7-171d-4172-b8ad-e71b5a9cd349.png)
Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/212122778-e3915182-0eda-4b0d-ab11-2389e42c231a.png)

2023-01-12 16:44 UTC, christianbiring1 commented on style.css
> +}
- [ ] As part of what I have said above. Kindly consider removing the individual `heigh` applied to these #ts elements

2023-01-12 16:44 UTC, christianbiring1 commented on style.css
> +}
- [ ] Kindly make sure you stick to the image as much as possible. the spacing, typo are supposed to match the figma design.
`Hint: You may consider making your image responsive by applying the:`
```css
width: 100%,
height: auto
// also you consider setting the
object-fit: container
```
- [ ] Kindly make sure the list element of `backend ...` are well aligned as in the template
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/212124706-e6690fb8-576f-4fc2-aef0-85698cd0f5c7.png)

The Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/212124864-33ea8e1b-a39c-4e97-9eeb-62dd0d498de8.png)

2023-01-12 16:44 UTC, christianbiring1 commented on index.html
> +                </div>
- [ ] Kindly make sure you have the correct fonts (family and size on your element)
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/212125774-8a7cc254-7947-4e80-8ef9-691d2f74c2b4.png)
Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/212125907-069af0f8-2733-4256-865a-bb257f19ea05.png)

2023-01-12 16:44 UTC, christianbiring1 commented on index.html
> +                    <li><a href="#"><img src="image/Vector.svg" alt="Vector"></a></li>
[OPTIONAL]
- [ ] It would be great to link these links to your social handlers.

2023-01-12 16:44 UTC, christianbiring1 commented on style.css
> +
- [ ] As is the case on the template, kindly make sure the buttons on your page follow the button styling: Active, Hover, and Pressed (see design)

![image](https://user-images.githubusercontent.com/97100091/212127125-7321daa1-77e0-4d2e-879a-100cbaa53bd2.png)

2023-01-13 08:15 UTC, bienvenuushindi approved these changes
# STATUS: APPROVED 🟢 

## Hi @Kaghenimbale   👋, 

Well done implementing the requested changes 👏
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/lJNoBCvQYp7nq/giphy.gif"/>

### Highlights 🎯 
:+1: No linter errors✔️
:+1: Good UI design✔️
:+1: Good PR title

### Optional Suggestions



**_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 10:04 UTC, merged