Mobile contact me
Kaghenimbale/my-portfolio pull request #4
Opened 2023-01-17 18:07 UTC by Kaghenimbale

- [ ]  Add a Name field that accepts up to 30 chars.
- [ ]  Add an Email field that accepts only emails.
- [ ]  Add a message field that accepts up to 500 chars.
- [ ]  Add in all fields placeholder text.
- [ ]  Add in all fields the correct type.

2023-01-17 18:58 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @Kaghenimbale, 
I'm Andres.

While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

- [ ] 🚧 Please consider adding a LICENSE to your project, at the moment, the link you provided in the README redirects to an external website. I suggest you follow [these steps](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) from the official GitHub docs in order to add a LICENSE to your project. Don't forget to link it in your README! 🤓 🔧  

![image](https://user-images.githubusercontent.com/77069011/212987184-bd32ca1f-88d0-4ed0-9f67-fc72d169e7e9.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 18:58 UTC, anagudelogu commented on index.html
> +            </form>
You did a good job working on this milestone! 💯 However, there's still some room to improve.

- [ ] 🚧 According to the requirements, you should use the `Formspree` service to collect data, please refer to their [documentation](https://formspree.io/html/) and implement this feature in your form! 🤓 🔧 

Overall, the design is good, but there are small issues that you could easily solve in order to make it even better. 🔧 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/212986022-6f6d5329-e3fa-49cc-b060-5309106bcbd5.png) | ![image](https://user-images.githubusercontent.com/77069011/212985850-aeb123b2-cfcc-467b-81f4-f8bed76494df.png) |

- [ ] 🚧 Please make sure to use the correct background image, as you can see, it is different from the one provided in the Figma template. 🔧 

- [ ] 🚧 Consider fixing the typo in the title `"Contacts"` ==> `"Contact"`. 🔧 

- [ ] 🚧 Please add some padding to your input fields, the text is very close to the edges! 🔧 

Applying those changes will improve the look and feel of this section of your page, so try to spend some time working on them! 🤓 🛠️

2023-01-17 18:58 UTC, anagudelogu commented on index.html
> +                        <textarea name="message" class="msg" maxlength="500" placeholder="Write your message here"></textarea>
- [ ] Good job applying the `maxlength` attribute to the `textarea` element! 🚀 Please make sure to make this field required too, according to the requirements, all the inputs should be required. 🤓 🔧 

From requirements:

![image](https://user-images.githubusercontent.com/77069011/212985244-3439e1c9-4cb5-479d-9154-bae041f5a311.png)

2023-01-18 06:12 UTC, Shedrack-Sunday requested changes
Hi @Kaghenimbale   👋 


# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing some of the suggested changes from the previous reviewer, but there are still some which aren't been addressed yet.
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked
✅ Descriptive commit messages 

Required Changes ♻️

- [ ] I must commend you for adding the form as suggested 👏  , but presently, there's a bug that doesn't get the form to submit the input text. Check the comment section for a more detailed review.

_check the comment section for a detailed review_

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.


Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-18 06:12 UTC, Shedrack-Sunday commented on index.html
> +            </form>
- [ ] Good job implementing the changes suggested by the previous reviewer. However, your form is not been successfully submitted. Kindly follow the [Guide here](https://formspree.io/html/), and make sure you don't miss anything. 

# Output:
![image](https://user-images.githubusercontent.com/50990925/213096847-8826be3d-0308-4e2e-a135-10f65ea8384e.png)

2023-01-18 06:39 UTC, PinkMoon25 approved these changes
Hi @Kaghenimbale , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/FerjqPHY2OGDPJPwEk/giphy.gif"/>

## Highlights
linter checks :heavy_check_mark: 
Integrate formspree :heavy_check_mark: 
form implementation :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 06:41 UTC, merged